# Generated by Django 5.2.1 on 2025-06-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='activity_type',
            field=models.CharField(choices=[('Running', 'Running'), ('Weightlifting', 'Weightlifting'), ('Cycling', 'Cycling'), ('Swimming', 'Swimming'), ('Yoga', 'Yoga'), ('Walking', 'Walking'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
