# Generated by Django 5.2.1 on 2025-06-22 12:35

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0003_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessentry',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='fitnessentry',
            name='title',
            field=models.CharField(default='Untitled Activity', max_length=100),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration',
            field=models.PositiveIntegerField(help_text='Duration in minutes'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Activity', max_length=100)),
                ('description', models.TextField()),
                ('date_earned', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_earned'],
            },
        ),
    ]
