# Generated by Django 5.2.1 on 2025-06-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0004_fitnessentry_date_fitnessentry_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessentry',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
