# Generated by Django 5.2.1 on 2025-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0005_fitnessentry_duration_alter_achievement_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
    ]
