# Generated by Django 5.2.1 on 2025-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitnessApp', '0007_alter_fitnessentry_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration',
            field=models.IntegerField(help_text='Duration in minutes'),
        ),
        migrations.AlterField(
            model_name='fitnessentry',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
