# Generated by Django 5.2.1 on 2025-06-04 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosts',
            new_name='JobPost',
        ),
    ]
